<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>アンケートの入力</title>
    <style>
        body {
            margin: 0;
            background-color: #f8f8f8;
        }
        form {
            margin: 0;
        }
        .wrap {
            width: 850px;
            margin-left: auto;
            margin-right: auto;
            background-color: #ffffff;
        }
        #nav{
            background-color: #ffffff;
            width: 100%;
            box-shadow: 0px 2px 10px -5px #a9a9a9;
            position: relative;
        }
        #nav #logout {
            width: 130px;
            position: absolute;
            top: 4px;
            right: 10px;
        } 
        #nav input[type="submit"] {
            background: none;
            display: block;
            text-align: center;
            border: 2px solid #e4555e;
            padding: 14px 30px;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer;
        } 
        #nav .wrap ul {
            display: flex;
            margin: 0;
            padding: 0;
            list-style-type: none;
        }
        #nav .wrap ul li {
            width: 25%;
            text-align: center;
        }
        #nav .wrap ul li form {
            margin: 0;
        }
        #nav .wrap ul li a {
            display: block;
            height: 20px;
            margin: 0;
            padding: 20px;
            color: #000000;
            text-decoration: none;
        }
        #nav ul li a:hover {
            box-shadow: 2px 2px 10px #a9a9a9;
        }
        #article {
            width: 850px;
            margin-left: auto;
            margin-right: auto;
        }
        #article h1 {
            margin: 0;
            margin: 40px 0;
            padding: 10px 0;
            background-color: #e4555e;
            color: #ffffff;
            text-align: center;
        }
        #article p {
            margin: 40px 0;
        }
        #article-box {
            padding: 10%;
            background-color: #ffffff;
            box-shadow: 2px 2px 10px #a9a9a9;
        }
        .item {
            display: inline-block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        .box {
            display: inline-block;
            width: 35px;
            background: #ff0000;
            border-radius: 2px;
            text-align: center;
        }
        .box span {
            color: #ffffff;
            font-size:0.7em;
            vertical-align: middle
        }
        /* phpの画像以外のスタイル */
        .img-position1 {
            width: 20px;
            position: relative;
            top: 4px;
        }
        /* phpの画像のスタイル */
        .img-position2 {        
            width: 22px;
        }
        #article input[type="submit"] {     
            background: none;
            display: block;
            margin: 40px auto;
            text-align: center;
            border: 2px solid #e4555e;
            padding: 14px 30px;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer;
        }
        #article input[type="submit"]:hover, #nav input[type="submit"]:hover{
            background: #e4555e;
        }
    </style>
</head>
<body>
	<div id="nav">
        <form method="POST" action="./index.php?event=logout" id="logout">
			<input type="submit" value="ログアウト">
		</form>
    	<div class="wrap">
            <ul>
                <li>
                    <form method="POST" name="form2" action ="index.php?event=check">
                        <a href="javascript:form2.submit()">調査アンケート</a>
                    </form>
                </li>
                <li>
                    <form action="./showGraph.php" name="form3" method="post">
                        <a href="javascript:form3.submit()">集計結果</a>
                    </form>
                </li>
                <li>
                    <form action="./index.php?event=bbs" name="form4" method="post">
                        <a href="javascript:form4.submit()">掲示板</a>
                    </form>
                </li>
                <li><a href="./views/input.html">検索</a></li>
            </ul>
        </div>
    </div>
    <div id="article">
        <h1>アンケート</h1>
        <p>以下のアンケートにご協力お願いします</p>
        <div id="article-box">
            <form method="POST" action="./index.php?event=receiveInput">
                <div class="item">Q1.今までにプログラミングを学習したことはありますか</div>　<div class="box"><span>必須</span></div><br>
                <input type="radio" name="q1" value="yes"><?= $view['q1_y'] ?>はい
                <input type="radio" name="q1" value="no"><?= $view['q1_n'] ?>いいえ<br><br>
                <div class="item">Q2.得意なプログラミング言語を教えてください</div>　<div class="box"><span>必須</span></div><br>
                <input type="radio" name="q2" value="html/css"><?= $view['q2_h'] ?>HTML/CSS
                <input type="radio" name="q2" value="php"><?= $view['q2_ph'] ?>PHP 
                <input type="radio" name="q2" value="java"><?= $view['q2_j'] ?>Java
                <input type="radio" name="q2" value="python"><?= $view['q2_py'] ?>Python
                <input type="radio" name="q2" value="other"><?= $view['q2_o'] ?>その他
                <input type="radio" name="q2" value="nothing"><?= $view['q2_n'] ?>未経験
        </div>
                <input type="submit" value="送信">
            </form>
    </div>
</body>
</html>