<html>
<head>
	<title>アンケート入力用ログイン</title>
	<style>
		body{
    		margin: 0;
    		padding: 0;
    		font-family: sans-serif;
    		background: #dbdbdb;
		}
		/*ログインフォームのエリア内のスタイル*/
		.box{
    		width: 300px;
    		padding: 40px;
    		position: absolute;
    		top: 50%;
    		left: 50%;
    		transform: translate(-50%, -50%);
    		background: #ffffff;
    		text-align: center;
		}
		.box{
    		text-transform: uppercase;
    		font-weight: 500;
		}
		/* ユーザーIDとパスワード入力ボックスのスタイル */
		.box input[type="text"], .box input[type="password"]{
    		border: 0;
    		background: none;
    		display: block;
    		margin: 20px auto;
    		text-align: center;
    		border: 2px solid #dbdbdb;
    		padding: 14px 10px;
    		width: 200px;
    		outline: none;
    		color: #000000;
    		border-radius: 24px;
    		transition: 0.25s;
		}
		/* 入力ボックスがフォーカスされたときのスタイル（幅が大きくなる＆枠の色が変わる） */
		.box input[type="text"]:focus, .box input[type="password"]:focus{
    		width: 280px;
    		border-color: #e4555e;
		}
		/* Loginボタンのスタイル */
		.box input[type="submit"]{
    		border: 0;
    		background: none;
    		display: block;
    		margin: 20px auto;
    		text-align: center;
    		border: 2px solid #e4555e;
    		padding: 14px 40px;
    		outline: none;
    		border-radius: 24px;
    		transition: 0.25s;
    		cursor: pointer;
		}
		/* Loginボタンをマウスオーバーしたときのスタイル */
		.box input[type="submit"]:hover{
    		background: #e4555e;
		}
	</style>
</head>
<body>
    <form class="box" method="POST" action="./index.php?event=checkLogin">
        <h1>sign in</h1>
		<font color="red">
			<?= nl2br(htmlspecialchars($view['errorMessage'])) ?>
		</font>
        <input type="text" name="username" placeholder="Username"
		value="<?= htmlspecialchars($view['username']) ?>">
        <input type="password" name="password" placeholder="Password">
        <input type="submit" value="Login">
    </form>
</body>
</html>
