<html>
<head>
<title>アルバイト一覧</title>
<style>
        body {
            margin: 0;
            background-color: #f8f8f8;
        }
        form {
            margin: 0;
        }
        .wrap {
            width: 850px;
            margin-left: auto;
            margin-right: auto;
            background-color: #ffffff;
        }
        #nav{
            background-color: #ffffff;
            width: 100%;
            box-shadow: 0px 2px 10px -5px #a9a9a9;
            position: relative;
        }
        #nav #logout {
            width: 130px;
            position: absolute;
            top: 4px;
            right: 10px;
        } 
        #nav input[type="submit"] {
            background: none;
            display: block;
            text-align: center;
            border: 2px solid #e4555e;
            padding: 14px 30px;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer;
        } 
        #nav .wrap ul {
            display: flex;
            margin: 0;
            padding: 0;
            list-style-type: none;
        }
        #nav .wrap ul li {
            width: 25%;
            text-align: center;
        }
        #nav .wrap ul li form {
            margin: 0;
        }
        #nav .wrap ul li a {
            display: block;
            height: 20px;
            margin: 0;
            padding: 20px;
            color: #000000;
            text-decoration: none;
        }
        #nav ul li a:hover {
            box-shadow: 2px 2px 10px #a9a9a9;
        }
        #article {
            width: 850px;
            margin-left: auto;
            margin-right: auto;
        }
        #article h1 {
            margin: 0;
            margin: 40px 0;
            padding: 10px 0;
            background-color: #e4555e;
            color: #ffffff;
            text-align: center;
        }
        #article p {
            margin: 40px 0;
        }
        #article-box {
            padding: 10%;
            background-color: #ffffff;
            box-shadow: 2px 2px 10px #a9a9a9;
        }
        .item {
            display: inline-block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        .box {
            display: inline-block;
            width: 35px;
            background: #ff0000;
            border-radius: 2px;
            text-align: center;
        }
        .box span {
            color: #ffffff;
            font-size:0.7em;
            vertical-align: middle
        }
        /* phpの画像以外のスタイル */
        .img-position1 {
            width: 20px;
            position: relative;
            top: 4px;
        }
        /* phpの画像のスタイル */
        .img-position2 {        
            width: 22px;
        }
        #article input[type="submit"] {     
            background: none;
            display: block;
            margin: 40px auto;
            text-align: center;
            border: 2px solid #e4555e;
            padding: 14px 30px;
            border-radius: 24px;
            transition: 0.25s;
            cursor: pointer;
        }
        #article input[type="submit"]:hover, #nav input[type="submit"]:hover{
            background: #e4555e;
        }
    </style>
</head>
<body>
	<div id="nav">
        <form method="POST" action="./index.php?event=logout" id="logout">
			<input type="submit" value="ログアウト">
		</form>
    	<div class="wrap">
            <ul>
                <li>
                    <form method="POST" name="form2" action ="index.php?event=check">
                        <a href="javascript:form2.submit()">調査アンケート</a>
                    </form>
                </li>
                <li>
                    <form action="./index.php?event=showAll" name="form3" method="post">
                        <a href="javascript:form3.submit()">一覧表示</a>
                    </form>
                </li>
                <li>
                    <form action="./index.php?event=bbs" name="form4" method="post">
                        <a href="javascript:form4.submit()">掲示板</a>
                    </form>
                </li>
                <li><a href="./views/input.html">検索</a></li>
            </ul>
        </div>
    </div>
	<div id="article">
		<h1>一覧表示</h1>
		<div id="article-box">
			<?php
			$dsn = 'mysql:dbname=kadai;host=localhost';
            $user = 'kadai';
            $passward = 'passward';

			try{
            $dbh = new PDO($dsn, $user, $passward);
			
    		$sql = 'select * from question';
    		foreach ($dbh->query($sql) as $row) {
				print("名前：".$row['name'].' ');
    		  	print("Q1：".$row['q1'].' ');
    		  	print("Q2：".$row['q2']);
    		  	print('<br>');
    		}
			}
			catch (PDOException $e){
    		print('Error:'.$e->getMessage());
    		die();
			}
			$dbh = null;
			?>
		</div>
		<form method="POST" action="index.php?event=check">
			<input type="submit" value="入力画面に戻る">
		</form>
	</div>
</body>
</html>